volumes:
  opensearch-data:

services:

  opensearch:
    image: opensearchproject/opensearch:latest
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=SuperSecretPassword123!"
      - "DISABLE_SECURITY_PLUGIN=true"

    ports:
      - "9200:9200"
      - "9600:9600"
