spring.application.name=simple-store
spring.threads.virtual.enabled=true

server.http2.enabled=true
server.shutdown=graceful
server.port=8080

opensearch.host=localhost
opensearch.port=9200
opensearch.scheme=http
opensearch.username=admin
opensearch.password=SuperSecretPassword123!

spring.data.redis.host=localhost
spring.data.redis.port=6379
